project:
  type: website
  output-dir: docs
  
website:
  title: "Cognition Blog"
  favicon: chrome_iPGQieatBJ.png
  navbar:
    right:
      - about.qmd
format:
  html:
    theme: 
      light: flatly
      dark: [vapor, custom.css]
      
  
    css: styles.css

editor: visual

